# golangci-lint v2 configuration for go-wallet-backend
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - unconvert
  disable:
    - exhaustive
    - unparam
    - gocritic
    - gosec
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: github.com/sirosfoundation/go-wallet-backend

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Fire-and-forget handler callbacks
    - linters:
        - errcheck
      text: "h\\.Error"
    - linters:
        - errcheck
      text: "h\\.Progress"
    - linters:
        - errcheck
      text: "h\\.ProgressMessage"
    # HTTP response body close in defer - best effort
    - linters:
        - errcheck
      text: "resp\\.Body\\.Close"
    # WebSocket deadline - best effort
    - linters:
        - errcheck
      text: "SetReadDeadline"
    # Fire-and-forget error reporting
    - linters:
        - errcheck
      text: "SendFlowError"

output:
  formats:
    colored-line-number: {}
  print-linter-name: true
  sort-results: true
